image: node:latest

stages:
    - test

cache:
  paths:
  - node_modules/

eslint:
    stage: test
    script:
        - npm install eslint
        - ./node_modules/.bin/eslint .

irc:
    stage: test
        script:
            - npm i
            - node ./ci/add-config.js
            - npm run test